### ISSUE TITLE
Core XPath functions that accept strings should implicitly convert arguments to a string

### ISSUE THREAD

**Issue by hgrecco** [shepmaster/sxd-xpath#113]
First let me say that I by no means an expert on XPath. Therefore I do not really know what does the spec say. Having said that, I was trying to achieve something similar to what is showing [here](https://stackoverflow.com/questions/3655549/xpath-containstext-some-string-doesnt-work-when-used-with-node-with-more). The expression `//*[text()[contains(.,'ABC')]]` was working perfectly in xpath tester sites such as [this](http://codebeautify.org/Xpath-Tester) but not with sxd-xpath. In order to make it work, I had to change it to: `//*[text()[contains(string(),'ABC')]]`  Is this a bug or the the other libraries are too permisive?

**Comment by shepmaster** [comment]
Hmm, that's a very good question!

[The spec has this to say for `contains`](https://www.w3.org/TR/xpath/#function-contains):

> Function: boolean contains(string, string)
>
> The contains function returns true if the first argument string contains the second argument string, and otherwise returns false.

The reason I chose the current behavior is because other functions, like [`string`](https://www.w3.org/TR/xpath/#function-string), explicitly say to convert the types.

That being said, [libxml2](https://github.com/GNOME/libxml2/blob/a07a4e96d04e802c291578a850a17797912249ab/xpath.c#L9058-L9063) and Xalan [C++](https://github.com/apache/xalan-c/blob/bb666d0ab3d0a192410823e6857c203d83c27b16/src/xalanc/XPath/FunctionContains.cpp#L56-L57) and [Java](https://github.com/apache/xalan-j/blob/c54cae05dcc64c25b42d546a85c8247873407654/src/org/apache/xpath/functions/FuncContains.java#L86-L87) all implicitly convert these to strings.

I think this library might be 10-15 years too late to try and forge a new path, so I'll probably need to bend to the majority will here... 😅
