### ISSUE TITLE
How to run an XPath query against a node in a nodeSet? 

### ISSUE THREAD

**Issue by babelchips** [shepmaster/sxd-xpath#127]
For example after using `evaluate_xpath(&document, &path)` to produce a `Nodeset` to iterate over, how would you then run a subsequent XPath query to drill down further using a relative XPath?

**Comment by shepmaster** [comment]
I don’t think there’s a straight-forward answer to your question, as I’m not sure that such a thing is defined via XPath itself. You should be able to use [`evaluate`][2] and normal iterator methods:

```rust
let nodes: Vec<_> = nodes.into_iter().filter_map(|n| {
    if let Ok(Value::Nodeset(ns)) = xpath.evaluate(&ctx, n) {
        Some(ns)
    } else {
        None
    }
}).flatten().collect()
```

Once you are using `evaluate`, you might as well use it everywhere. 

You may also want to look into evaluating just one XPath with additional constraints. For example, instead of `//foo[@bar]` and then `.//baz`, do `//foo[@bar][.//baz]`.

Complicated conditional logic can also be pushed into the XPath by making an [XPath function][3]. 


[2]: https://docs.rs/sxd-xpath/0.4.2/sxd_xpath/struct.XPath.html#method.evaluate
[3]: https://docs.rs/sxd-xpath/0.4.2/sxd_xpath/context/struct.Context.html

**Comment by babelchips** [comment]
Thank you.  This lets me deal with a large XML data in separate parts - drilling down into parts of the tree and then doing further XPath queries from there.
