### ISSUE TITLE
Public Expression::evaluate() returns private Error

### ISSUE THREAD

**Issue by flying-sheep** [shepmaster/sxd-xpath#67]
[the expression crate is private](http://jakegoulding.com/sxd-xpath/sxd_xpath/trait.Expression.html#tymethod.evaluate)
```rust
pub trait Expression: Debug {
    fn evaluate<'a, 'd>(&self, context: &sxd_xpath::EvaluationContext<'a, 'd>)
        -> Result<sxd_xpath::Value<'d>, sxd_xpath::expression::Error>;
}
```

so if i’m not missing something, this crate is actually unusable for its main purpose: evaluating XPath expressions :laughing:

**Comment by shepmaster** [comment]
As I run off to work, I'll point to the [integration test](https://github.com/shepmaster/sxd-xpath/blob/master/tests/integration.rs), which should exercise it as a user would. I'm sure I need to document something better; perhaps we can figure out what that something is.

**Comment by flying-sheep** [comment]
surely ok()ping and unwrap()ing everything works, but useful error inspection is of course also necessary in some cases.

`xpath.evaluate(&context)` here returns a `Result<Value<'d>, expression::Error>`. the `expression::Error` class is private, so anything except from `Error` trait methods (`description`) is lost.

> I need to document something better

**any**thing would be a start :wink: 

but yeah, you can learn well from the integration tests if you find them (what i did)

**Comment by shepmaster** [comment]
You started by saying

> unusable for its main purpose: evaluating XPath expressions

Which would imply that it is **impossible** to evaluate an expression. Is this true, or are you able to evaluate expressions, but the real problem is that the `expression::Error` type is private so any useful messages cannot be retrieved? Or are you hoping that the `expression::Error` type would have more information than the `Error` trait?

Perhaps I would understand better if you could include a small reproducible example of the code you've written and what you are trying to do.

**Comment by flying-sheep** [comment]
oh, sorry, of course it’s not impossible!


small code example:

```rust
use sxd_xpath::expression;

...

match xpath.evaluate(&context) {
	Ok(value) => ...,
	Err(e) => match e {
            UnknownFunction(f) => //do stuff with f,
            UnknownVariable(v) => //do stuff with v,
            _ => ()
        }
}
```
